app/assets/stylesheets/home.scss
=> Added styles to body

app/assets/stylesheets/home.scss
I made changes to the css file
=> added more styles to css

app/assets/javascripts/shell/shell.html, app/assets/stylesheets/_colors.scss, app/assets/stylesheets/home.scss, app/assets/stylesheets/shell.scss
Team, there are two commits here...
(1) We should be sure to write this at the top of each of our .scss files:
@import 'colors';
and be sure to use color variables instead of hard-coded color codes and names.
This will allow us to easily make changes to our color theme in one location.
Ben, feel free to set up the color theme in the _colors.scss file.
(2) The second commit changed the layout of the shell to allow for a fixed header & footer with a scrolling app area.
=> Two commits: (1) added _colors.scss; (2) modified shell.html for fixed footer & header

app/assets/javascripts/shell/shell.html, app/assets/stylesheets/_colors.scss, app/assets/stylesheets/shell.scss
=> Un-revert!

app/models/restaurant.rb, app/models/suggestion_box.rb, app/models/vote.rb, db/migrate/20150131004317_create_votes.rb, db/migrate/20150131004732_create_restaurants.rb, db/migrate/20150131004825_create_suggestion_boxes.rb, db/schema.rb, spec/models/restaurant_spec.rb, spec/models/suggestion_box_spec.rb, spec/models/vote_spec.rb
this is my model portion. i added model - vote / restaurant / suggestionbox
=> added model vote restaurant suggestionbox

app/models/potential_dish.rb, app/models/suggestion.rb, app/models/trash_talk.rb, db/migrate/20150131005143_create_potential_dishes.rb, db/migrate/20150131005332_create_suggestions.rb, db/migrate/20150131005608_create_trash_talks.rb, db/schema.rb, spec/models/potential_dish_spec.rb, spec/models/suggestion_spec.rb, spec/models/trash_talk_spec.rb
=> Update schema and add models potential dish suggenstion and trash talk

app/assets/javascripts/app-module.js, app/assets/javascripts/home/home.html
Added skeleton routes, folders, pages & controllers for battle, winners, about, register & restaurant.  FYI, the links are just for demonstration purposes.  The app's actual links will be dynamically generated in layout.html.
=> Added skeleton routes, folders, pages & controllers

db/seeds.rb
=> as a git test, added comments to seeds.rb

Gemfile, Gemfile.lock, db/schema.rb, spec/factories/counties.rb, spec/factories/users.rb, spec/models/battle_spec.rb, spec/models/county_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb
Please merge these updated tests for the User and County model.  Lots of more tests coming soon!
=> refactored user tests to use FactoryGirl

db/migrate/20150202165101_change_year_month_to_date.rb
For some reason this file was still stuck in my git status as a file still being tracked.
=> Reupload Change Year Month to Date

app/models/restaurant.rb, db/migrate/20150203033356_add_columns_name_location_phone_yelp_to_restaurant.rb
I added to the restaurant model new columns
=> Added to Restaurant model columns name location phone and yelp urls

app/models/suggestion_box.rb, spec/factories/battles.rb, spec/factories/counties.rb, spec/factories/potential_dishes.rb, spec/factories/suggestion_boxes.rb, spec/factories/suggestions.rb, spec/factories/trash_talks.rb, spec/models/cuisine_lookup_spec.rb, spec/models/dish_spec.rb, spec/models/potential_dish_spec.rb, spec/models/suggestion_box_spec.rb, spec/models/suggestion_spec.rb, spec/models/trash_talk_spec.rb
=> added battle factory

db/schema.rb, spec/factories/battles.rb, spec/models/battle_spec.rb
Team - please merge this pull request.  Then pull into your master branch.  IMPORTANT - YOU WILL NEED TO RUN "rake db:migrate" after pulling.
=> all tests done for battle model - need to run db:migrate after pull

spec/factories/battles.rb, spec/factories/suggestion_boxes.rb, spec/models/battle_spec.rb, spec/models/suggestion_box_spec.rb, spec/models/trash_talk_spec.rb, spec/models/vote_spec.rb
=> added tests for suggestion_box, trash_talk & vote models

spec/factories/battles.rb
=> changed battles factory

app/models/trash_talk.rb
=> validated trash talk - ALL GREEN

app/assets/javascripts/app-module.js, app/assets/javascripts/home/home.html, app/assets/javascripts/register/register.html, app/assets/javascripts/signup/signup-controller.js, app/assets/javascripts/signup/signup.html
Please review the updated register to signup files and folder structure
=> Refractor register name to signup

app/assets/stylesheets/_colors.scss, app/assets/stylesheets/foundation_and_overrides.scss, app/assets/stylesheets/home.scss, app/assets/stylesheets/shell.scss, app/models/trash_talk.rb
default colors are working properly.
=> added uniform colors, set primary/secondary colors default

app/controllers/users_controller.rb
=> replaced line of code that got deleted in user_controller.login_token

app/assets/javascripts/shell/shell-controller.js, app/controllers/application_controller.rb, app/controllers/battles_controller.rb, app/controllers/users_controller.rb, config/routes.rb, db/test_seeds.rb, spec/controllers/battles_controller_spec.rb, spec/rails_helper.rb
=> Added create

app/assets/javascripts/common/yelp-service.js
=> stubbed up ng YelpService

app/assets/javascripts/shell/shell.html
Css for nav bar still needs to be tweaked (i.e. nav bar height), but elements of nav bar seem to be there. Will work with Ben to make sure elements are in working order.
=> Icon and drop down menu added on shell html page

Gemfile, Gemfile.lock, app/assets/javascripts/common/battle-service.js, app/controllers/battles_controller.rb
=> added userCanVote function to battle-service.js

app/assets/javascripts/app-module.js, app/assets/javascripts/common/user-service.js, app/assets/javascripts/common/yelp-service.js, app/assets/javascripts/nominate/nominate-controller.js, app/assets/javascripts/nominate/nominate.html, app/assets/stylesheets/nominate.scss
=> search restaurants added on nominate.html

app/assets/javascripts/common/yelp-service.js
=> finished consolidating of chain restaurants in yelp-service.js

app/assets/javascripts/shell/shell.html, app/assets/stylesheets/shell.scss
=> removed section tag from header and re-postiioned user elements

app/assets/javascripts/winners/winners-controller.js, app/assets/javascripts/winners/winners.html
Edwin, the vm.winners property in winners-controller.js holds all previously completed battles.  It is an array of battle objects.  Each battle object has the same data that you're used to working with.  The first battle in the array (vm.winners[0]), is last month's battle, and the last battle in the array is the oldest.
=> hooked up winners data to winners-controller.js

app/assets/javascripts/battle/battle-controller.js, app/assets/javascripts/battle/battle.html, app/assets/javascripts/nominate/nominate-controller.js, app/assets/stylesheets/battle.scss
=> added upvote modal to battle page

app/assets/javascripts/about/about.html, app/assets/javascripts/battle/battle.html, app/assets/javascripts/winners/winners.html, app/assets/stylesheets/about.scss, app/assets/stylesheets/battle.scss, app/assets/stylesheets/home.scss, app/assets/stylesheets/shell.scss, app/assets/stylesheets/winners.scss
tuned up minor touches here. i'm still working on the restaurant page and modal.
=> tuned up about page/home page. battle page/greateight/finalfour ready

app/assets/javascripts/battle/battle.html, app/assets/javascripts/nominate/nominate.html, app/assets/stylesheets/battle.scss, app/assets/stylesheets/home.scss, app/assets/stylesheets/nominate.scss
=> added more styling

app/assets/javascripts/battle/battle.html, app/assets/javascripts/restaurant/restaurant.html, app/assets/stylesheets/battle.scss, app/assets/stylesheets/nominate.scss, app/assets/stylesheets/restaurant.scss
=> current status
